from pathlib import Path
from html import escape
import json
accessory_data=json.loads((Path(__file__).parent/"accessory-catalog.json").read_text())
root=Path(__file__).resolve().parents[1]/'store'
v='20260928-45'
photos={
'lower':'https://tcevolutions.com/cdn/shop/files/Damage_Counter_Dice_TCEVOLUTIONS_3.jpg?v=1742269932&width=1200',
'higher':'https://tcevolutions.com/cdn/shop/files/Damage_Counter_Dice_TCEVOLUTIONS_2.jpg?v=1742347748&width=1200',
'ability':'https://tcevolutions.com/cdn/shop/files/bk-closeup-metal-pokemon-tcg-markers-aluminum-us.jpg?v=1768006715&width=1200',
'condition':'https://tcevolutions.com/cdn/shop/files/7B2783A1-62B4-43B6-96C0-BC7A64C24586.png?v=1782411405&width=1200'}
products=[dict(id='lower',name='ローダメージ',range='10〜120',desc='10〜60を表示するカウンターが4個、70〜120が2個。小さなダメージを刻む場面や、ダメカンを少しずつのせる場面に。',rows=[('10・20・30・40・50・60','12mm / 4個'),('70・80・90・100・110・120','13mm / 2個')]),dict(id='higher',name='ハイダメージ',range='130〜240',desc='130〜180を表示するカウンターが4個、190〜240が2個。大きなダメージを、複数の小さなカウンターに分けずに表示できます。',rows=[('130・140・150・160・170・180','13mm / 4個'),('190・200・210・220・230・240','14mm / 2個')])]
colors=[('blue','ブルー','#0075be'),('cyan','シアン','#00bad5'),('gold','ゴールド','#c99a36'),('green','グリーン','#25934d'),('gunmetal','ガンメタル','#626971'),('magenta','マゼンタ','#d51d84'),('orange','オレンジ','#ed8319'),('purple','パープル','#8041ba'),('red','レッド','#d83240'),('silver','シルバー','#c9cdd2')]
def color_picker(product):
 folder=product["id"]; stem="high" if folder=="higher" else "low"; ext="png" if folder=="higher" else "webp"
 return '<fieldset class="color-picker"><legend>カラー</legend><div class="color-options">'+''.join(f'<label class="color-option"><input type="radio" name="product-color" value="{key}" data-color-label="{name}" data-color-src="../assets/{folder}/{stem}_damage_counter_{key}.{ext}" {"checked" if key=="blue" else ""}><span class="color-dot" style="--swatch:{tone}"></span><span class="sr-only">{name}</span></label>' for key,name,tone in colors)+'</div><button type="button" class="color-pause" data-color-pause aria-label="カラー画像の自動切り替えを停止">Ⅱ</button><p class="small" data-color-status role="status" aria-live="polite"></p></fieldset>'
def photo(k,eager=False,prefix='./',color='blue'):
 if k in accessory_data:
  return f'<img src="{accessory_data[k]["images"][0]}" alt="TCEvolutions {dict(ability="特性使用済みマーカー",condition="どく・やけどマーカー",case="アルミ収納ケース")[k]}の公式商品写真" width="1200" height="1200" loading="{"eager" if eager else "lazy"}">'
 if k in ('lower','higher'):
  stem='high' if k=='higher' else 'low';ext='png' if k=='higher' else 'webp';name='ハイダメージ' if k=='higher' else 'ローダメージ';color_name=dict((c,n) for c,n,_ in colors)[color]
  return f'<img class="product-color-image" data-product-name="{name}" src="{prefix}assets/{k}/{stem}_damage_counter_{color}.{ext}" alt="{name}・{color_name}のカラーイメージ" width="384" height="341" loading="{"eager" if eager else "lazy"}">'

 return f'<img src="{photos[k]}" alt="TCEvolutions {dict(lower="ローダメージ6個入り",higher="ハイダメージ6個入り",ability="特性使用済みマーカー",condition="やけど・どくマーカー")[k]}のメーカー商品写真" width="1200" height="1200" loading="{"eager" if eager else "lazy"}">'
def head(title,desc,p='./'):
 return f'<!doctype html>\n<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#191919"><meta name="description" content="{escape(desc)}"><title>{title}｜TAIBAL SUPPLY</title><link rel="stylesheet" href="{p}styles.css?v={v}"></head><body><a class="skip-link" href="#main">本文へ</a>'
def header(p='./'):
 return f'''<div class="announcement">11月1日 発売 <span>初回入荷分限定・予約受付中</span></div>
<header class="site-header"><div class="wrap nav"><a class="brand" href="{p}" aria-label="TAIBAL SUPPLY ホーム">TAIBAL<span>SUPPLY</span></a><nav aria-label="メインメニュー"><a data-test-link href="{p}#products">商品一覧</a><a data-test-link href="{p}story.html">TCEの物語</a><a data-test-link href="{p}#faq">ご利用案内</a></nav><button class="cart-trigger" data-cart-open aria-haspopup="dialog" aria-controls="cart-dialog">カート <span data-cart-count>0</span></button></div></header>'''
def footer(p='./'):
 return f'''<footer><div class="wrap footer-grid"><div><a class="brand" href="{p}">TAIBAL<span>SUPPLY</span></a><p>色と質感で選ぶ、海外の上質なカードサプライ。</p></div><div class="footer-links"><a href="{p}legal.html">特定商取引法に基づく表記</a><a href="{p}privacy.html">プライバシーポリシー</a><a href="mailto:torataku777@gmail.com">お問い合わせ</a></div></div></footer>'''
def cart(p='./'):
 return f'''<div class="cart-dock" data-cart-dock hidden><div><span data-dock-count></span><strong data-dock-total></strong><small data-dock-discount></small></div><button class="button" data-cart-open>カートを見る <span aria-hidden="true">→</span></button></div>
<dialog id="cart-dialog" class="cart-dialog" aria-labelledby="cart-title"><div class="cart-header"><div><p class="eyebrow">選んだ商品</p><h2 id="cart-title">カート</h2></div><button class="close-button" data-cart-close aria-label="カートを閉じる" autofocus>×</button></div><div class="cart-scroll"><div data-cart-empty><p class="empty-title">カートに商品が入っていません。</p><p>商品を選んで、組み合わせと金額を確認できます。</p><button class="button" data-cart-close>商品を選ぶ</button></div><div data-cart-content hidden><div data-cart-items></div><div class="cart-offer" data-cart-offer></div><div class="cart-totals"><div><span>商品小計</span><span data-subtotal></span></div><div class="discount-row" data-discount-row hidden><span>まとめ買い割引 <small data-pairs></small></span><strong data-discount></strong></div><div class="total-row"><span>商品合計 <small>税込</small></span><strong data-total></strong></div><div class="shipping-estimate"><div><span>送料</span><span data-shipping-estimate></span></div><div><strong>送料込み合計</strong><strong data-estimated-total></strong></div><p class="small">国内送料350円。割引後の商品合計10,000円以上で送料無料。</p></div></div><div class="checkout-area"><p class="launch-note" data-launch-note><strong>2026年11月1日発売・予約受付中</strong><span>予約商品です。ご注文時に全額をお支払いいただき、2026年11月1日以降、入荷・検品後に順次発送予定です。対応する数量・組み合わせはカートでご確認ください。</span></p><a class="button checkout-link" data-checkout hidden>予約の決済へ</a><p class="small" data-checkout-status hidden></p><a class="checkout-help" data-checkout-help hidden>この内容で相談する →</a><p class="preorder-scope">オンライン予約：単品1点、ロー＋ハイ各1点、マーカー2種類各1点、4種類各1点、ケース付きフルセット各1点。その他の数量・組み合わせは個別にご案内します。</p><button class="continue-button" data-cart-close>商品選びを続ける</button></div></div></div><p class="sr-only" data-cart-announcement role="status" aria-live="polite"></p></dialog>
<div class="toast" role="status" aria-live="polite" data-toast hidden></div><noscript><p class="wrap noscript">カートを使うにはJavaScriptを有効にしてください。商品情報は各詳細ページでご覧いただけます。</p></noscript>
<script src="{p}checkout-config.js?v={v}"></script><script src="{p}cart-model.js?v={v}"></script><script src="{p}app.js?v={v}"></script><script src="{p}color-picker.js?v={v}"></script><script src="{p}preorder.js?v={v}"></script><script src="{p}experience.js?v={v}"></script></body></html>'''
def contents_summary(p):
 return '<div class="contents-summary"><p>6個入りの内訳</p>'+''.join(f'<div><span class="face-values">'+''.join(f'<span>{n}</span>' for n in nums.split('・'))+f'</span><strong>× {qty.split(" / ")[1]}</strong></div>' for nums,qty in p['rows'])+'<small>各カウンターの6面に刻印された数字</small></div>'
upcoming=[dict(id='ability',name='特性使用済みマーカー',desc='特性を使ったポケモンの目印に。'),dict(id='condition',name='どく・やけどマーカー',desc='特殊状態を、カードのそばに表示。'),dict(id='case',name='収納ケース（仕切り付き）',desc='専用の仕切りで、カウンターとマーカーを整頓。')]
accessory_specs={
 'ability':('2個入り / 裏返して使用状況を表示','裏返すだけで、特性の使用状況を表示。アルマイトの色と切削された銀色の縁が、手元に表情を添えます。','2個入り','アルミニウム / アルマイト処理'),
 'condition':('どく・やけど 各1個 / 厚さ2.5mm','どくは緑、やけどは赤。レーザー刻印のシンボルで特殊状態を見分けられます。銀色の縁を残したアルミ製マーカーです。','どく・やけど 各1個','6061アルミニウム / 厚さ2.5mm'),
 'case':('仕切り付き / アルミ製 / マグネット開閉','黒いアルミボディに、色を効かせた縁取り。4か所のマグネットでふたを閉じる、カウンター・マーカー用の収納ケースです。','ケース1個＋専用インサート（仕切り）1個。ダイス・マーカーは付属しません。','アルミ削り出し / 2トーンアルマイト処理')
}
future_prices={'lower':5480,'higher':5480,'ability':3280,'condition':3280,'case':10980,'damage':10480,'marker':5980,'tournament':15980,'complete':22800}
initial_prices={'lower':4980,'higher':4980,'ability':2980,'condition':2980,'case':8980,'damage':9480,'marker':5480,'tournament':13980,'complete':19800}
def launch_price(key):
 current=initial_prices[key]; future=future_prices[key]
 return f'<div class="initial-price"><span class="initial-label">初回入荷分限定</span><span class="future-price"><span>11月1日以降の販売予定価格</span><s>¥{future:,}</s></span><div class="initial-price-main"><strong>¥{current:,}<small>税込</small></strong><span class="initial-saving">{future-current:,}円お得</span></div></div>'
def reference_price(key):
 return launch_price(key)+'<p class="small">国内送料350円。割引後の商品合計10,000円以上で送料無料。</p>'
def bundle_offer(key,title,contents,button):
 return f'<article><p>{title}</p>{launch_price(key)}<p class="small">{contents}</p><button class="bundle-cart" type="button" data-add-bundle="{key}">{button} <span>＋</span></button></article>'
def gallery(item):
 images=accessory_data[item['id']]['images']
 thumbs=''.join(f'<button type="button" class="gallery-thumb" data-gallery-src="{url}" data-gallery-alt="{item["name"]}・公式商品写真 {n+1}" aria-label="商品写真{n+1}を表示" aria-pressed="{str(n==0).lower()}"><img src="{url.replace("width=1200","width=160")}" alt="" loading="lazy" width="80" height="80"></button>' for n,url in enumerate(images))
 return f'<div class="detail-gallery" data-gallery><div class="detail-photo gallery-stage"><button class="gallery-zoom" type="button" aria-label="商品写真を拡大"><img data-gallery-main src="{images[0]}" alt="{item["name"]}・公式商品写真 1" width="1200" height="1200"></button><span class="coming-badge">予約受付中</span><span class="zoom-hint">クリックで拡大 ↗</span></div><div class="gallery-controls"><button type="button" data-gallery-prev aria-label="前の商品写真">←</button><span data-gallery-count aria-live="polite">1 / {len(images)}</span><button type="button" data-gallery-next aria-label="次の商品写真">→</button></div><div class="gallery-thumbs" aria-label="商品写真一覧">{thumbs}</div><p class="catalog-note">TCEvolutions公式の商品写真。写真のカラーは参考イメージです。{"ケース内のダイス・マーカーは付属しません。" if item["id"]=="case" else ""}</p><dialog class="image-dialog" aria-label="商品写真の拡大"><button type="button" data-gallery-close aria-label="拡大画像を閉じる">×</button><img alt=""></dialog></div>'
def upcoming_card(item):
 visual=photo(item['id'])
 return f'''<article class="shop-product upcoming-product"><a class="shop-photo" href="./products/{item['id']}.html" aria-label="{item['name']}の商品詳細">{visual}<span class="coming-badge">予約受付中</span></a><div class="shop-product-body"><div class="product-heading"><div><p class="product-brand">TCEvolutions</p><h3>{item['name']}</h3></div></div><p class="product-descriptor">{item['desc']}</p><details class="product-disclosure"><summary>商品詳細を開く</summary><p class="small">{accessory_specs[item['id']][0]}</p></details><div class="product-bottom">{launch_price(item['id'])}<a class="detail-link" href="./products/{item['id']}.html">商品詳細を見る ↗</a></div><button class="button add-button" data-add="{item['id']}" aria-label="{item['name']}を予約カートに入れる">予約カートに入れる <span aria-hidden="true">＋</span></button></div></article>'''
def card(p):
 return f'''<article class="shop-product"><a class="shop-photo" data-test-link href="./products/{p['id']}.html" aria-label="{p['name']}の商品詳細">{photo(p['id'],color='blue' if p['id']=='lower' else 'magenta')}<span class="photo-label">予約 / 6個入り</span></a><div class="shop-product-body"><div class="product-heading"><div><p class="product-brand">TCEvolutions</p><h3>{p['name']}</h3></div><p class="range">{p['range']}<small>表示できるダメージ</small></p></div><p class="product-descriptor">アルミ削り出し / 6個入り / 全10色</p><details class="product-disclosure"><summary>商品詳細を開く</summary>{contents_summary(p)}</details><div class="product-bottom">{launch_price(p['id'])}<a class="detail-link" data-test-link href="./products/{p['id']}.html">10色を見る <span aria-hidden="true">↗</span></a></div><button class="button add-button" data-add="{p['id']}" aria-label="{p['name']}を予約カートに入れる">予約カートに入れる <span aria-hidden="true">＋</span></button></div></article>'''
index=head('TCEvolutions｜上質な金属製サプライ','デッキに似合う10色と、アルミ削り出しの金属光沢。色と仕上げにこだわるTCEvolutionsのダメージカウンター・マーカー・収納ケース。対象の組み合わせでまとめ買い割引。')+header()+f'''<main id="main">
<section class="hero"><img class="hero-scene" src="./assets/tce-tabletop-lit.webp" alt="金属製ダメージカウンター、マーカー、収納ケースを卓上に並べたコーディネートイメージ" width="1448" height="1086" fetchpriority="high"><div class="hero-veil"></div><div class="wrap hero-inner"><div class="hero-copy"><p class="hero-brand">TCEvolutions</p><p class="eyebrow">上質な金属製カードサプライ</p><h1><span>対戦を、</span><span>もっと美しく。</span></h1><p class="hero-lead"><span>デッキに似合う色を、</span><span>アルミの輝きで。</span></p><p class="hero-description">好きなデッキに、好きな色と質感を。<br>アルミを削り出したカウンターとマーカーで、<br>対戦の道具にも、自分らしいこだわりを。</p><a class="button hero-cta" href="#products">予約する商品を選ぶ <span aria-hidden="true">→</span></a><p class="hero-price"><span>初回予約 / ダメージカウンター 各6個</span><strong>¥4,980</strong><small>税込・送料別</small></p></div></div><p class="hero-caption">コーディネートイメージ / ケース・マーカー等は6個入り商品に含まれません。</p></section>
<div class="benefit-strip"><div class="wrap benefit-grid"><div><span class="benefit-index">01</span><p><strong>アルミならではの輝き</strong><span>削り出しの質感と金属光沢</span></p></div><div><span class="benefit-index">02</span><p><strong>デッキに合わせる10色</strong><span>タイプやスリーブと揃える楽しさ</span></p></div><div><span class="benefit-index">03</span><p><strong>国内からお届け</strong><span>入荷後に検品して発送</span></p></div></div></div>
<section class="reservation-guide wrap" id="reservation"><div><p class="eyebrow">2026.11.01 発売</p><h2>初回入荷分だけの、予約価格。</h2><p>初回入荷分は、10月31日までの特別価格。11月1日以降は表示の販売予定価格に切り替えます。</p></div><div class="reservation-steps"><p><strong>予約する</strong><span>商品とカラーを選び、予約時にお支払い。</span></p><p><strong>11月1日以降、順次発送</strong><span>国内で検品してからお届けします。発売日当日の到着をお約束するものではありません。</span></p><p><strong>送料350円・1万円以上で無料</strong><span>割引後の商品合計で判定します。入荷が遅れる場合はメールでご案内します。</span></p></div></section>
<section id="products" class="section wrap catalog"><span id="accessories" class="anchor-alias"></span><span id="singles" class="anchor-alias"></span><span id="sets" class="anchor-alias"></span><div class="section-heading"><div><p class="eyebrow">商品ラインナップ</p><h2><span class="heading-line">使う数字で選ぶ。</span><span class="heading-line">好きな色で揃える。</span></h2></div><p>10色のカウンター、銀色の縁が際立つマーカー、<br>アルミの収納ケース。色と仕上げで選ぶTCEvolutions。</p></div><div class="shop-grid">{card(products[0])}{card(products[1])}{"".join(upcoming_card(item) for item in upcoming)}</div><div class="bundle-offers" id="bundle-review"><div class="bundle-offers-heading"><p class="eyebrow">まとめ買い割引</p><h3>組み合わせて、お得に。</h3><p>単品をカートに追加すると、対象の割引を自動で適用します。</p></div><div class="complete-offer">{bundle_offer('complete','ケースまで揃う、TCEフルセット','ケース・専用仕切り各1個／ダメカン12個／特性使用済み2個・どく1個・やけど1個。送料無料。','フルセットをカートへ')}<p class="small">初回予約の単品合計24,900円から5,100円お得。収納写真はイメージです。仕切りの仕様はメーカー確認後にご案内します。</p></div><div class="bundle-offer-grid">{bundle_offer('damage','ローダメージ ＋ ハイダメージ','カウンター計12個。送料350円。','2種類をカートへ')}{bundle_offer('marker','特性使用済み ＋ どく・やけど','特性使用済み2個・どく1個・やけど1個。送料350円。','2種類をカートへ')}{bundle_offer('tournament','ダメージ2種類 ＋ マーカー2種類','カウンター計12個・マーカー計4個。送料無料。','4種類をカートへ')}</div><div class="bundle-offers-footer"><p>各種類1点ずつで適用。ケースまで揃えるフルセットも対象です。<br>価格は税込。値引き額は同じ商品の11月1日以降の販売予定価格との比較です。初回予約価格は2026年10月31日23:59（日本時間）まで。</p><button class="bundle-cart" data-cart-open>カートで金額を確認する →</button></div></div><p class="catalog-note">ダメージカウンターは各商品詳細で10色のカラーイメージを確認できます。全商品が予約対象です。2026年11月1日以降、入荷・検品後に順次発送予定です。</p></section>
<section id="craft" class="craft-section"><div class="wrap craft-grid"><div class="craft-photo"><img src="https://cdn.shopify.com/s/files/1/0813/2188/6018/files/IMG_7184_480x480.jpg?v=1693871287" alt="アルマイト加工の保持部分が付いた、製造途中のアルミ製カウンター" width="480" height="480" loading="lazy"><p>メーカー公開の製造工程写真</p></div><div class="craft-copy"><p class="eyebrow">TCEvolutionsのものづくり</p><h2>アルミを削り出し、<br>数字を刻む。</h2><p>アルミの塊から、着色中に固定するための突起まで一体で削り出す。着色後は突起を除き、加工跡にも配慮して数字を刻む。完成品の仕上がりを支える工程があります。</p><p>ダイスの目を10倍して読み替える必要がなく、<br>表示された数字でダメージを確認できます。</p><a class="detail-link" href="./story.html#story-craft">削り出しと仕上げのこだわりを読む →</a></div></div></section>
<section id="story" class="section wrap story-grid"><div><p class="eyebrow">ブランドのはじまり</p><h2>きっかけは、<br>息子とのポケカでした。</h2><span class="story-year" aria-hidden="true">2016</span><figure class="story-preview-photo"><img src="./assets/story/father-son.jpg" alt="公式ストーリーページに掲載されたSteveとAaronの親子写真" width="960" height="639" loading="lazy"><figcaption>写真：TCEvolutions公式サイト</figcaption></figure></div><div><p>2016年、当時11歳だったAaronは、ダイスの目を10倍してダメージを計算するのに苦戦していました。</p><p>ダイスに数字が書いてあれば、もっとわかりやすい。息子の発想を受け止めた父Steveは、製造業の経験を生かして開発に取り組みました。</p><p>表面の仕上がりや色を調整し、数か月の試作を重ねて、2016年後半に最初の試作品が完成。親子の対戦で生まれた小さな気づきが、TCEvolutionsの出発点でした。</p><p>作り手自身もプレイヤーとして、使いやすさと仕上がりを追求。活動は、ほかのTCGや店舗・大会コミュニティとの協力へと広がっています。</p><a class="detail-link" href="./story.html">TCEが生まれた物語を読む →</a></div></section>
<section id="faq" class="section wrap faq-grid"><div><p class="eyebrow">ご利用案内</p><h2>よくあるご質問</h2></div><div class="faq"><details><summary>1点に何個入っていますか？</summary><p>ローダメージ・ハイダメージは各6個入り、特性使用済みマーカーは2個入り、どく・やけどマーカーは各1個入りです。収納ケースは本体と専用インサート（仕切り）を各1個セットでお届けします。写真内のダイス・マーカーは付属しません。</p></details><details><summary>まとめ買い割引の条件を教えてください。</summary><p>ローダメージとハイダメージ各1点で480円引き、特性使用済みマーカーとどく・やけどマーカー各1点で480円引きです。4種類を各1点揃えるとさらに980円引きとなり、割引合計は1,940円、商品合計は13,980円（税込）です。現在のオンライン決済は、各種類1点ずつの掲載セットに対応しています。同じ種類だけの購入はセット割引対象外です。ケースを含む5種類各1点は19,800円（税込・送料無料）になります。</p></details><details><summary>予約時の支払いと発送はいつですか？</summary><p>全商品を予約注文として受け付けています。予約時に全額をお支払いいただきます。予約受付は2026年10月31日まで。2026年11月1日以降、入荷・検品を終えた商品から順次発送予定です。単品各1点、ロー＋ハイ各1点、マーカー2種類各1点、4種類各1点、ケース付きフルセット各1点の組み合わせに対応しています。それ以外の数量・組み合わせはお問い合わせください。カートに入れただけでは注文は確定せず、決済完了で受付となります。</p></details><details><summary>メイン写真の商品がすべて届きますか？</summary><p>メイン写真はコーディネートイメージです。収納ケース・マーカー・カードなどは、6個入りのダメージカウンターに含まれません。購入する商品の内容は、各商品ページでご確認ください。</p></details><details><summary>カラーは選べますか？</summary><p>ローダメージ・ハイダメージともに10色のカラーイメージを掲載しています。各商品詳細で選んだカラーをカートに追加できます。色違いは別々に表示され、カート内でもカラーを変更できます。カラーの異なるロー・ハイもまとめ買い割引の対象です。決済画面でカラーを再選択してください。決済画面の選択内容でご注文を受け付けます。</p></details><details><summary>送料とお届け時期を教えてください。</summary><p>TAIBAL SUPPLYが国内で受け取り、検品してから発送します。国内送料は350円です。割引後の税込商品合計が10,000円以上の場合は送料無料です。2026年11月1日以降、入荷・検品を終えた商品から順次発送予定です。入荷・検品後に順次発送します。入荷・配送状況により前後する場合があります。お届けが遅れる場合は、ご注文時のメールアドレスへご案内します。</p></details><details><summary>TCEvolutionsとの関係を教えてください。</summary><p>TAIBAL SUPPLYはTCEvolutionsから直接仕入れ、国内で販売します。日本総代理店・独占代理店ではありません。</p></details></div></section><section class="closing-section"><div class="wrap"><p class="eyebrow">TCEvolutions / TAIBAL SUPPLY</p><h2>対戦を、もっと美しく。</h2><a class="button" href="#products">商品を選ぶ <span aria-hidden="true">→</span></a></div></section></main>'''+footer()+cart()
index=index.replace('</head>',"<meta property=\"og:type\" content=\"website\"><meta property=\"og:locale\" content=\"ja_JP\"><meta property=\"og:title\" content=\"11月1日発売・予約受付中｜TCEvolutions\"><meta property=\"og:description\" content=\"デッキに似合う色と、アルミ削り出しの質感。ダメージカウンター・マーカー・収納ケースを予約受付中。国内送料350円、1万円以上で送料無料。\"><meta property=\"og:url\" content=\"https://torataku777-debug.github.io/taibal-supply/store/\"><meta property=\"og:image\" content=\"https://torataku777-debug.github.io/taibal-supply/store/assets/lower/low_damage_counter_blue.webp\"><meta name=\"twitter:card\" content=\"summary_large_image\"></head>")
root.joinpath('index.html').write_text(index)
for p in products:
 other=next(q for q in products if q!=p)
 official_gallery=(Path(__file__).parent/(p['id']+'-official-gallery.html')).read_text()
 rows=''.join(f'<div><dt>{nums}</dt><dd>{qty}</dd></div>' for nums,qty in p['rows'])
 html=head(p['name']+' ダメージカウンター 6個入り',p['desc'],'../')+header('../')+f'''<main id="main"><div class="wrap breadcrumb"><a href="../#products">商品一覧</a><span>/</span><span>{p['name']}</span></div><section class="wrap product-detail"><div class="detail-gallery"><div class="detail-photo">{photo(p['id'],True,'../')}<span class="photo-label">予約 / 6個入り</span></div><p class="catalog-note">カラーを選んでカートに追加できます。追加すると画像の自動切り替えが止まります。</p></div><div class="detail-copy"><p class="eyebrow">TCEvolutions / アルミ製ダメージカウンター</p><h1>{p['name']}</h1><p class="detail-range">{p['range']}<span>のダメージを表示 / 6個入り</span></p>{launch_price(p['id'])}<p class="purchase-note">6個入り・ケース別売り。国内送料350円。割引後の商品合計10,000円以上で送料無料。</p><p class="quality-note">アルミ削り出しの質感と、光を受けて変わる色の表情。デッキやスリーブに合わせてお選びください。</p><details class="product-disclosure"><summary>商品詳細を開く</summary><p class="detail-description">{p['desc']}</p>{contents_summary(p)}</details>{color_picker(p)}<a class="button preorder-link" data-preorder href="../preorder.html?product={p['id']}">予約内容を確認する <span>→</span></a><button class="button add-button" data-add="{p['id']}" aria-label="{p['name']}を予約カートに入れる">予約カートに入れる <span aria-hidden="true">＋</span></button><p class="detail-discount">{other['name']}と各1点で、合計9,480円（税込）。<br>単品合計9,960円から480円引き。<br>割引はカートに自動で反映されます。</p><p class="launch-note"><strong>2026年11月1日発売・予約受付中</strong><span>カートから予約の決済へ進めます。入荷・配送状況により、お届け時期が前後する場合があります。</span></p></div></section>{official_gallery}<section class="section wrap detail-bottom"><div><p class="eyebrow">商品内容</p><h2>6個の内訳</h2><p class="small">各カウンターの6面に、以下の数字が刻印されています。</p><dl class="spec-list">{rows}<div><dt>素材・加工</dt><dd>アルミニウム / CNC加工</dd></div><div><dt>カラー</dt><dd>全10色</dd></div></dl></div><div><p class="eyebrow">組み合わせて使う</p><h2>{other['range']}も必要な方へ</h2><a class="related-product" data-test-link href="{other['id']}.html">{photo(other['id'],False,'../')}<div><h3>{other['name']}</h3><p>6個入り / ¥4,980（税込）</p><span class="detail-link">商品詳細を見る ↗</span></div></a><p class="small">両方を各1点選ぶと、12個で9,480円（税込）。<br>国内送料350円。割引後の商品合計10,000円以上で送料無料。</p></div></section><section class="section wrap related-accessories"><h2>マーカーも一緒に</h2><div class="related-accessory-links"><a href="ability.html">特性使用済みマーカー <span>→</span></a><a href="condition.html">どく・やけどマーカー <span>→</span></a></div></section></main>'''+footer('../')+cart('../')
 root.joinpath('products',p['id']+'.html').write_text(html)
# Existing bundle URLs continue to work, but lead into the same individual-product cart.
for slug,is_full in [('damage-full',False),('tournament-full',True)]:
 title='ダメージカウンターの組み合わせ' if not is_full else 'ダメージカウンター・マーカーのご案内'
 extra='<p>4種類を各1点選ぶと、商品合計13,980円（税込）です。特性使用済みマーカーとどく・やけどマーカーは、それぞれ単品2,980円（税込）です。</p><a class="detail-link" href="../#products">商品一覧へ →</a>' if is_full else '<button class="button" data-add-pair>ローダメージとハイダメージを各1点入れる <span aria-hidden="true">＋</span></button>'
 html=head(title,'デッキに似合う色と、使う数字で選ぶ。対象の組み合わせでまとめ買い割引。','../')+header('../')+f'''<main id="main" class="section wrap legacy-page"><p class="eyebrow">商品選びのご案内</p><h1>{title}</h1><p>ローダメージとハイダメージは、それぞれ6個入り・4,980円（税込）。必要な種類をカートに追加してお選びください。</p><p>両方を各1点選ぶと、480円のまとめ買い割引が自動で適用されます。商品合計は9,480円（税込）です。</p><div class="legacy-products"><a href="lower.html">{photo('lower',True,'../')}<h2>ローダメージ</h2><p>10〜120 / 6個入り</p></a><a href="higher.html">{photo('higher',True,'../')}<h2>ハイダメージ</h2><p>130〜240 / 6個入り</p></a></div>{extra}</main>'''+footer('../')+cart('../')
 root.joinpath('products',slug+'.html').write_text(html)
print('Built store homepage and four product pages')

def accessory_related(key):
 if key in ('ability','condition'):
  return '<div><p class="eyebrow">マーカーを揃える</p><h2>特性と特殊状態を、見分けやすく。</h2><p class="detail-description">特性使用済みとどく・やけどの2種類で5,480円（税込）。単品合計から480円引き。</p><p class="small">1種類を選んだあと、もう1種類を追加すると商品合計は2,500円増えます。</p><button class="button" data-add-bundle="marker">マーカー2種類をカートへ <span>＋</span></button></div>'
 return '<div><p class="eyebrow">あわせて選ぶ</p><h2>ダメージカウンター</h2><p class="detail-description">ロー・ハイ各1点で9,480円（税込）。カウンターはケースに含まれません。</p><button class="button" data-add-pair>ロー・ハイを各1点カートへ <span>＋</span></button></div>'

# Shared detail-page structure for upcoming accessory products.
accessories=[dict(id='ability',name='特性使用済みマーカー',label='ABILITY USED',desc='特性を使ったことを、カードのそばでわかりやすく。'),dict(id='condition',name='どく・やけどマーカー',label='状態異常マーカー',desc='どく・やけどの状態を、カードのそばに表示。'),dict(id='case',name='収納ケース（仕切り付き）',label='カウンター・マーカー用',desc='対戦に使うカウンターやマーカーを、ひとつにまとめて。')]
for item in accessories:
 spec=accessory_specs[item['id']]
 html=head(item['name'],item['desc'],'../')+header('../')+f'''<main id="main"><div class="wrap breadcrumb"><a href="../#products">商品一覧</a><span>/</span><span>{item['name']}</span></div><section class="wrap product-detail">{gallery(item)}<div class="detail-copy"><p class="eyebrow">TCEvolutions / {item['label']}</p><h1>{item['name']}</h1><p class="detail-description">{item['desc']}</p><p class="product-descriptor">{spec[0]}</p>{reference_price(item['id'])}<details class="product-disclosure"><summary>商品詳細を開く</summary><p class="detail-description">{spec[1]}</p></details><a class="button preorder-link" href="../preorder.html?product={item['id']}">予約内容を確認する <span>→</span></a><button class="button add-button" data-add="{item['id']}" aria-label="{item['name']}を予約カートに入れる">予約カートに入れる <span>＋</span></button><p class="launch-note"><strong>予約受付中</strong><span>2026年11月1日以降、順次発送予定です。入荷・配送状況により前後する場合があります。カートから予約の決済へ進めます。</span></p><a class="detail-link accessory-back" href="../#products">商品一覧へ →</a></div></section><section class="section wrap detail-bottom"><div><p class="eyebrow">商品について</p><h2>商品情報</h2><dl class="spec-list"><div><dt>内容</dt><dd>{spec[2]}</dd></div><div><dt>素材・加工</dt><dd>{spec[3]}</dd></div><div><dt>販売価格</dt><dd>¥{accessory_data[item['id']]['planned_jpy']:,}（税込・送料別）</dd></div></dl><p class="small">メーカー情報確認日：2026年9月26日</p><a class="detail-link" href="{accessory_data[item['id']]['source']}" target="_blank" rel="noopener noreferrer">メーカーの商品情報を見る ↗</a></div>{accessory_related(item['id'])}</section></main>'''+footer('../')+cart('../')
 root.joinpath('products',item['id']+'.html').write_text(html)

story=head('TCEが生まれた物語','親子の気づきから始まったTCEvolutions。試作の経緯、アルミの加工・着色、プレイヤーとともに歩むものづくり。')+header()+(Path(__file__).parent/'story-content.html').read_text()+footer()+cart()
root.joinpath('story.html').write_text(story)
preorder=head('予約注文について','予約商品の内容・カラー・数量とお支払い金額の確認。')+header()+'''<main class="wrap preorder-page section" id="main"><p class="eyebrow">予約注文</p><h1>予約内容の確認</h1><p class="launch-note"><strong>予約商品について</strong><span>2026年11月1日以降、入荷・検品を終えた商品から順次発送予定です。商品をカートに追加し、内容と送料を確認して決済へ進んでください。決済完了で予約注文を受け付けます。</span></p><form data-preorder-form><label>商品<select name="product"><option value="lower">ローダメージ 6個入り</option><option value="higher">ハイダメージ 6個入り</option><option value="ability">特性使用済みマーカー</option><option value="condition">どく・やけどマーカー</option><option value="case">収納ケース（仕切り付き）</option></select></label><label data-preorder-color>カラー<select name="color">'''+''.join(f'<option value="{key}">{name}</option>' for key,name,_ in colors)+'''</select></label><label>数量<input name="quantity" type="number" value="1" min="1" max="99" step="1"></label><p data-preorder-total role="status"></p><p class="small">2026年11月1日以降、順次発送予定です。入荷・配送状況により前後する場合があります。国内送料350円、割引後の商品合計10,000円以上で送料無料。</p><button class="button" type="submit">カートで内容を確認する</button></form><a class="detail-link" href="./#products">商品一覧へ戻る →</a></main>'''+footer()+cart()
root.joinpath('preorder.html').write_text(preorder)

