from pathlib import Path
from html import escape
import json
accessory_data=json.loads((Path(__file__).parent/"accessory-catalog.json").read_text())
root=Path(__file__).resolve().parents[1]/'store'
v='20260926-29'
photos={
'lower':'https://tcevolutions.com/cdn/shop/files/Damage_Counter_Dice_TCEVOLUTIONS_3.jpg?v=1742269932&width=1200',
'higher':'https://tcevolutions.com/cdn/shop/files/Damage_Counter_Dice_TCEVOLUTIONS_2.jpg?v=1742347748&width=1200',
'ability':'https://tcevolutions.com/cdn/shop/files/bk-closeup-metal-pokemon-tcg-markers-aluminum-us.jpg?v=1768006715&width=1200',
'condition':'https://tcevolutions.com/cdn/shop/files/7B2783A1-62B4-43B6-96C0-BC7A64C24586.png?v=1782411405&width=1200'}
products=[dict(id='lower',name='ローダメージ',range='10〜120',desc='10〜60を表示するカウンターが4個、70〜120が2個。小さなダメージを刻む場面や、ダメカンを少しずつのせる場面に。',rows=[('10・20・30・40・50・60','12mm / 4個'),('70・80・90・100・110・120','13mm / 2個')]),dict(id='higher',name='ハイダメージ',range='130〜240',desc='130〜180を表示するカウンターが4個、190〜240が2個。大きなダメージを、複数の小さなカウンターに分けずに表示できます。',rows=[('130・140・150・160・170・180','13mm / 4個'),('190・200・210・220・230・240','14mm / 2個')])]
colors=[('blue','ブルー','#0075be'),('cyan','シアン','#00bad5'),('gold','ゴールド','#c99a36'),('green','グリーン','#25934d'),('gunmetal','ガンメタル','#626971'),('magenta','マゼンタ','#d51d84'),('orange','オレンジ','#ed8319'),('purple','パープル','#8041ba'),('red','レッド','#d83240'),('silver','シルバー','#c9cdd2')]
def color_picker(product):
 folder=product["id"]; stem="high" if folder=="higher" else "low"; ext="png" if folder=="higher" else "webp"
 return '<fieldset class="color-picker"><legend>カラー</legend><div class="color-options">'+''.join(f'<label class="color-option"><input type="radio" name="product-color" value="{key}" data-color-label="{name}" data-color-src="../assets/{folder}/{stem}_damage_counter_{key}.{ext}" {"checked" if key=="blue" else ""}><span class="color-dot" style="--swatch:{tone}"></span><span class="sr-only">{name}</span></label>' for key,name,tone in colors)+'</div><button type="button" class="color-pause" data-color-pause aria-label="カラー画像の自動切り替えを停止">Ⅱ</button><p class="small" data-color-status role="status" aria-live="polite"></p></fieldset>'
def photo(k,eager=False,prefix='./',color='blue'):
 if k in accessory_data:
  return f'<img src="{accessory_data[k]["images"][0]}" alt="TCEvolutions {dict(ability="特性使用済みマーカー",condition="どく・やけどマーカー",case="アルミ収納ケース")[k]}の公式商品写真" width="1200" height="1200" loading="{"eager" if eager else "lazy"}">'
 if k in ('lower','higher'):
  stem='high' if k=='higher' else 'low';ext='png' if k=='higher' else 'webp';name='ハイダメージ' if k=='higher' else 'ローダメージ';color_name=dict((c,n) for c,n,_ in colors)[color]
  return f'<img class="product-color-image" data-product-name="{name}" src="{prefix}assets/{k}/{stem}_damage_counter_{color}.{ext}" alt="{name}・{color_name}のカラーイメージ" width="384" height="341" loading="{"eager" if eager else "lazy"}">'

 return f'<img src="{photos[k]}" alt="TCEvolutions {dict(lower="ローダメージ6個入り",higher="ハイダメージ6個入り",ability="特性使用済みマーカー",condition="やけど・どくマーカー")[k]}のメーカー商品写真" width="1200" height="1200" loading="{"eager" if eager else "lazy"}">'
def head(title,desc,p='./'):
 return f'<!doctype html>\n<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#191919"><meta name="description" content="{escape(desc)}"><title>{title}｜TAIBAL SUPPLY</title><link rel="stylesheet" href="{p}styles.css?v={v}"></head><body><a class="skip-link" href="#main">本文へ</a>'
def header(p='./'):
 return f'''<div class="announcement">2026年10月 入荷予定 <span>ただいま販売準備中</span></div>
<header class="site-header"><div class="wrap nav"><a class="brand" href="{p}" aria-label="TAIBAL SUPPLY ホーム">TAIBAL<span>SUPPLY</span></a><nav aria-label="メインメニュー"><a data-test-link href="{p}#products">商品一覧</a><a data-test-link href="{p}story.html">TCEの物語</a><a data-test-link href="{p}#faq">ご利用案内</a></nav><button class="cart-trigger" data-cart-open aria-haspopup="dialog" aria-controls="cart-dialog">カート <span data-cart-count>0</span></button></div></header>'''
def footer(p='./'):
 return f'''<footer><div class="wrap footer-grid"><div><a class="brand" href="{p}">TAIBAL<span>SUPPLY</span></a><p>海外のカードサプライを、国内からお届け。</p></div><div class="footer-links"><a href="{p}legal.html">特定商取引法に基づく表記</a><a href="{p}privacy.html">プライバシーポリシー</a><a href="mailto:torataku777@gmail.com">お問い合わせ</a></div></div></footer>'''
def cart(p='./'):
 return f'''<div class="cart-dock" data-cart-dock hidden><div><span data-dock-count></span><strong data-dock-total></strong><small data-dock-discount></small></div><button class="button" data-cart-open>カートを見る <span aria-hidden="true">→</span></button></div>
<dialog id="cart-dialog" class="cart-dialog" aria-labelledby="cart-title"><div class="cart-header"><div><p class="eyebrow">選んだ商品</p><h2 id="cart-title">カート</h2></div><button class="close-button" data-cart-close aria-label="カートを閉じる" autofocus>×</button></div><div class="cart-scroll"><div data-cart-empty><p class="empty-title">カートに商品が入っていません。</p><p>商品を選んで、組み合わせと予定金額を確認できます。</p><button class="button" data-cart-close>商品を選ぶ</button></div><div data-cart-content hidden><div data-cart-items></div><div class="cart-offer" data-cart-offer></div><div class="cart-totals"><div><span>商品小計</span><span data-subtotal></span></div><div class="discount-row" data-discount-row hidden><span>まとめ買い割引 <small data-pairs></small></span><strong data-discount></strong></div><div class="total-row"><span>商品合計 <small>税込・予定価格</small></span><strong data-total></strong></div><p class="small">送料は販売開始前にご案内します。</p></div><div class="checkout-area"><p class="launch-note" data-launch-note><strong>2026年10月 入荷予定</strong><span>現在は販売準備中です。カートに入れても注文・予約にはなりません。表示金額は販売予定価格です。</span></p><a class="button checkout-link" data-checkout hidden>購入手続きへ</a><p class="small" data-checkout-status hidden></p><button class="continue-button" data-cart-close>商品選びを続ける</button></div></div></div><p class="sr-only" data-cart-announcement role="status" aria-live="polite"></p></dialog>
<div class="toast" role="status" aria-live="polite" data-toast hidden></div><noscript><p class="wrap noscript">カートを使うにはJavaScriptを有効にしてください。商品情報は各詳細ページでご覧いただけます。</p></noscript>
<script src="{p}checkout-config.js?v={v}"></script><script src="{p}cart-model.js?v={v}"></script><script src="{p}app.js?v={v}"></script><script src="{p}color-picker.js?v={v}"></script><script src="{p}preorder.js?v={v}"></script><script src="{p}experience.js?v={v}"></script></body></html>'''
def contents_summary(p):
 return '<div class="contents-summary"><p>6個入りの内訳</p>'+''.join(f'<div><span class="face-values">'+''.join(f'<span>{n}</span>' for n in nums.split('・'))+f'</span><strong>× {qty.split(" / ")[1]}</strong></div>' for nums,qty in p['rows'])+'<small>各カウンターの6面に刻印された数字</small></div>'
upcoming=[dict(id='ability',name='特性使用済みマーカー',desc='特性を使ったポケモンの目印に。'),dict(id='condition',name='どく・やけどマーカー',desc='特殊状態を、カードのそばに表示。'),dict(id='case',name='収納ケース',desc='カウンターとマーカーをまとめて。')]
accessory_specs={
 'ability':('2個入り / アルミ削り出し','裏返すだけで、特性の使用状況を表示。アルマイトの色と切削された銀色の縁が、手元に表情を添えます。','2個入り','アルミニウム / アルマイト処理'),
 'condition':('どく・やけど 各1個 / 厚さ2.5mm','どくは緑、やけどは赤。レーザー刻印のシンボルで特殊状態を見分けられます。銀色の縁を残したアルミ製マーカーです。','どく・やけど 各1個','6061アルミニウム / 厚さ2.5mm'),
 'case':('アルミ製 / マグネット開閉 / ver.2','黒いアルミボディに、色を効かせた縁取り。4か所のマグネットでふたを閉じる、カウンター・マーカー用の収納ケースです。','ケース1個。写真内のダイス・マーカーは付属しません。','アルミ削り出し / 2トーンアルマイト処理')
}
def reference_price(key):
 return f'<div class="reference-price planned-price"><small>販売予定価格</small><strong>¥{accessory_data[key]["planned_jpy"]:,} <small>税込</small></strong><p class="small">発売前の予定価格です。送料は別途ご案内します。</p></div>'
def gallery(item):
 images=accessory_data[item['id']]['images']
 thumbs=''.join(f'<button type="button" class="gallery-thumb" data-gallery-src="{url}" data-gallery-alt="{item["name"]}・公式商品写真 {n+1}" aria-label="商品写真{n+1}を表示" aria-pressed="{str(n==0).lower()}"><img src="{url.replace("width=1200","width=160")}" alt="" loading="lazy" width="80" height="80"></button>' for n,url in enumerate(images))
 return f'<div class="detail-gallery" data-gallery><div class="detail-photo gallery-stage"><button class="gallery-zoom" type="button" aria-label="商品写真を拡大"><img data-gallery-main src="{images[0]}" alt="{item["name"]}・公式商品写真 1" width="1200" height="1200"></button><span class="coming-badge">Coming Soon</span><span class="zoom-hint">クリックで拡大 ↗</span></div><div class="gallery-controls"><button type="button" data-gallery-prev aria-label="前の商品写真">←</button><span data-gallery-count aria-live="polite">1 / {len(images)}</span><button type="button" data-gallery-next aria-label="次の商品写真">→</button></div><div class="gallery-thumbs" aria-label="商品写真一覧">{thumbs}</div><p class="catalog-note">TCEvolutions公式の商品写真。写真のカラーは参考イメージです。{"ケース内のダイス・マーカーは付属しません。" if item["id"]=="case" else ""}</p><dialog class="image-dialog" aria-label="商品写真の拡大"><button type="button" data-gallery-close aria-label="拡大画像を閉じる">×</button><img alt=""></dialog></div>'
def upcoming_card(item):
 visual=photo(item['id'])
 return f'''<article class="shop-product upcoming-product"><a class="shop-photo" href="./products/{item['id']}.html" aria-label="{item['name']}の商品詳細">{visual}<span class="coming-badge">Coming Soon</span></a><div class="shop-product-body"><div class="product-heading"><div><p class="product-brand">TCEvolutions</p><h3>{item['name']}</h3></div></div><p class="product-descriptor">{item['desc']}</p><details class="product-disclosure"><summary>商品詳細を開く</summary><p class="small">{accessory_specs[item['id']][0]}</p></details><div class="product-bottom"><p class="reference-price planned-price"><small>販売予定価格</small><strong>¥{accessory_data[item['id']]['planned_jpy']:,} <small>税込</small></strong></p><a class="detail-link" href="./products/{item['id']}.html">商品詳細を見る ↗</a></div><button class="button add-button" data-add="{item['id']}" aria-label="{item['name']}をカートに入れる">カートに入れる <span aria-hidden="true">＋</span></button></div></article>'''
def card(p):
 return f'''<article class="shop-product"><a class="shop-photo" data-test-link href="./products/{p['id']}.html" aria-label="{p['name']}の商品詳細">{photo(p['id'],color='blue' if p['id']=='lower' else 'magenta')}<span class="photo-label">6個入り</span></a><div class="shop-product-body"><div class="product-heading"><div><p class="product-brand">TCEvolutions</p><h3>{p['name']}</h3></div><p class="range">{p['range']}<small>表示できるダメージ</small></p></div><p class="product-descriptor">アルミ削り出し / 6個入り / 全10色</p><details class="product-disclosure"><summary>商品詳細を開く</summary>{contents_summary(p)}</details><div class="product-bottom"><p class="price">¥5,480 <small>税込</small></p><a class="detail-link" data-test-link href="./products/{p['id']}.html">10色を見る <span aria-hidden="true">↗</span></a></div><button class="button add-button" data-add="{p['id']}" aria-label="{p['name']}をカートに入れる">カートに入れる <span aria-hidden="true">＋</span></button></div></article>'''
index=head('TCEvolutions ダメージカウンター','デッキに似合う10色と、アルミ削り出しの金属光沢。TCEvolutionsのアルミ製ダメージカウンターを6個入り1点から。対象の組み合わせでまとめ買い割引。')+header()+f'''<main id="main">
<section class="hero"><img class="hero-scene" src="./assets/tce-tabletop-lit.webp" alt="金属製ダメージカウンター、マーカー、収納ケースを卓上に並べたコーディネートイメージ" width="1448" height="1086" fetchpriority="high"><div class="hero-veil"></div><div class="wrap hero-inner"><div class="hero-copy"><p class="hero-brand">TCEvolutions</p><p class="eyebrow">こだわりのポケカサプライ</p><h1><span>対戦を、</span><span>もっと美しく。</span></h1><p class="hero-lead"><span>デッキに似合う色を、</span><span>アルミの輝きで。</span></p><p class="hero-description">デッキのタイプやスリーブに合わせて選べる10色。<br>光を受けてきらめく金属光沢と、削り出しの質感を手元に。</p><a class="button hero-cta" href="#products">ダメージカウンターを選ぶ <span aria-hidden="true">→</span></a><p class="hero-price"><span>6個入り</span><strong>¥5,480</strong><small>税込</small></p></div></div><p class="hero-caption">コーディネートイメージ / ケース・マーカー等は6個入り商品に含まれません。</p></section>
<div class="benefit-strip"><div class="wrap benefit-grid"><div><span class="benefit-index">01</span><p><strong>アルミならではの輝き</strong><span>削り出しの質感と金属光沢</span></p></div><div><span class="benefit-index">02</span><p><strong>デッキに合わせる10色</strong><span>タイプやスリーブと揃える楽しさ</span></p></div><div><span class="benefit-index">03</span><p><strong>国内からお届け</strong><span>入荷後に検品して発送</span></p></div></div></div>
<section id="products" class="section wrap catalog"><span id="accessories" class="anchor-alias"></span><span id="singles" class="anchor-alias"></span><span id="sets" class="anchor-alias"></span><div class="section-heading"><div><p class="eyebrow">商品ラインナップ</p><h2><span class="heading-line">使う数字で選ぶ。</span><span class="heading-line">好きな色で揃える。</span></h2></div><p>全10色のダメージカウンターと、発売予定のマーカー・ケース。<br>デッキに合わせて、手元の道具を選べます。</p></div><div class="shop-grid">{card(products[0])}{card(products[1])}{"".join(upcoming_card(item) for item in upcoming)}</div><div class="bundle-offers"><div class="bundle-offers-heading"><p class="eyebrow">まとめ買い割引</p><h3>組み合わせると、合計が変わる。</h3><p>単品をカートに追加すると、対象の割引を自動で適用します。</p></div><div class="bundle-offer-grid"><article><p>ローダメージ ＋ ハイダメージ</p><strong>¥10,480<small>税込</small></strong><span>単品合計 ¥10,960 / 480円引き</span><p class="small">カウンター計12個</p><button class="bundle-cart" type="button" data-add-bundle="damage">2種類をカートへ <span>＋</span></button></article><article><p>特性使用済み ＋ どく・やけど</p><strong>¥5,980<small>税込</small></strong><span>単品合計 ¥6,560 / 580円引き</span><p class="small">特性使用済み2個・どく1個・やけど1個</p><button class="bundle-cart" type="button" data-add-bundle="marker">2種類をカートへ <span>＋</span></button></article><article><p>ダメージ2種類 ＋ マーカー2種類</p><strong>¥15,980<small>税込</small></strong><span>単品合計 ¥17,520 / 1,540円引き</span><p class="small">カウンター計12個・マーカー計4個</p><button class="bundle-cart" type="button" data-add-bundle="tournament">4種類をカートへ <span>＋</span></button></article></div><div class="bundle-offers-footer"><p>販売予定価格・送料別。各種類1点ずつを1組として適用。<br>収納ケースは割引対象外です。4種類の割引額は合計1,540円です。</p><button class="bundle-cart" data-cart-open>カートで金額を確認する →</button></div></div><p class="catalog-note">ダメージカウンターは各商品詳細で10色のカラーイメージを確認できます。販売開始は入荷後にご案内します。</p></section>
<section id="craft" class="craft-section"><div class="wrap craft-grid"><div class="craft-photo"><img src="https://cdn.shopify.com/s/files/1/0813/2188/6018/files/IMG_7184_480x480.jpg?v=1693871287" alt="アルマイト加工の保持部分が付いた、製造途中のアルミ製カウンター" width="480" height="480" loading="lazy"><p>メーカー公開の製造工程写真</p></div><div class="craft-copy"><p class="eyebrow">TCEvolutionsのものづくり</p><h2>アルミを削り出し、<br>数字を刻む。</h2><p>アルミの塊から、着色中に固定するための突起まで一体で削り出す。着色後は突起を除き、加工跡にも配慮して数字を刻む。完成品の仕上がりを支える工程があります。</p><p>ダイスの目を10倍して読み替える必要がなく、<br>表示された数字でダメージを確認できます。</p><a class="detail-link" href="./story.html#story-craft">削り出しと仕上げのこだわりを読む →</a></div></div></section>
<section id="story" class="section wrap story-grid"><div><p class="eyebrow">ブランドのはじまり</p><h2>きっかけは、<br>息子とのポケカでした。</h2><span class="story-year" aria-hidden="true">2016</span><figure class="story-preview-photo"><img src="./assets/story/father-son.jpg" alt="公式ストーリーページに掲載されたSteveとAaronの親子写真" width="960" height="639" loading="lazy"><figcaption>写真：TCEvolutions公式サイト</figcaption></figure></div><div><p>2016年、当時11歳だったAaronは、ダイスの目を10倍してダメージを計算するのに苦戦していました。</p><p>ダイスに数字が書いてあれば、もっとわかりやすい。息子の発想を受け止めた父Steveは、製造業の経験を生かして開発に取り組みました。</p><p>表面の仕上がりや色を調整し、数か月の試作を重ねて、2016年後半に最初の試作品が完成。親子の対戦で生まれた小さな気づきが、TCEvolutionsの出発点でした。</p><p>作り手自身もプレイヤーとして、使いやすさと仕上がりを追求。活動は、ほかのTCGや店舗・大会コミュニティとの協力へと広がっています。</p><a class="detail-link" href="./story.html">TCEが生まれた物語を読む →</a></div></section>
<section id="faq" class="section wrap faq-grid"><div><p class="eyebrow">ご利用案内</p><h2>よくあるご質問</h2></div><div class="faq"><details><summary>1点に何個入っていますか？</summary><p>ローダメージ・ハイダメージは各6個入り、特性使用済みマーカーは2個入り、どく・やけどマーカーは各1個入りです。収納ケースはケース本体1個で、中に写っているダイス・マーカーや別売りインサートは含まれません。</p></details><details><summary>まとめ買い割引の条件を教えてください。</summary><p>ローダメージとハイダメージ各1点で480円引き、特性使用済みマーカーとどく・やけどマーカー各1点で580円引きです。4種類を各1点揃えるとさらに480円引きとなり、割引合計は1,540円、商品合計は15,980円（税込・予定価格）です。各組み合わせの数量に応じて繰り返し適用します。同じ種類だけの購入と収納ケースは対象外です。</p></details><details><summary>いま注文できますか？</summary><p>現在は販売準備中で、初回入荷は2026年10月を予定しています。カートでは商品の組み合わせと金額を確認できますが、注文・予約・在庫の確保は行われません。販売開始日は、このサイトでお知らせします。</p></details><details><summary>メイン写真の商品がすべて届きますか？</summary><p>メイン写真はコーディネートイメージです。収納ケース・マーカー・カードなどは、6個入りのダメージカウンターに含まれません。購入する商品の内容は、各商品ページでご確認ください。</p></details><details><summary>カラーは選べますか？</summary><p>ローダメージ・ハイダメージともに全10色です。各商品詳細で選んだカラーをカートに追加できます。色違いは別々に表示され、カート内でもカラーを変更できます。カラーの異なるロー・ハイもまとめ買い割引の対象です。現在は販売準備中です。</p></details><details><summary>送料と発送日数を教えてください。</summary><p>TAIBAL SUPPLYが国内で受け取り、検品してから発送します。送料・発送日数・返品条件は、販売開始前に掲載します。</p></details><details><summary>TCEvolutionsとの関係を教えてください。</summary><p>TAIBAL SUPPLYはTCEvolutionsから直接仕入れ、国内で販売します。日本総代理店・独占代理店ではありません。</p></details></div></section><section class="closing-section"><div class="wrap"><p class="eyebrow">TCEvolutions / TAIBAL SUPPLY</p><h2>対戦を、もっと美しく。</h2><a class="button" href="#products">商品を選ぶ <span aria-hidden="true">→</span></a></div></section></main>'''+footer()+cart()
root.joinpath('index.html').write_text(index)
for p in products:
 other=next(q for q in products if q!=p)
 official_gallery=(Path(__file__).parent/(p['id']+'-official-gallery.html')).read_text()
 rows=''.join(f'<div><dt>{nums}</dt><dd>{qty}</dd></div>' for nums,qty in p['rows'])
 html=head(p['name']+' ダメージカウンター 6個入り',p['desc'],'../')+header('../')+f'''<main id="main"><div class="wrap breadcrumb"><a href="../#products">商品一覧</a><span>/</span><span>{p['name']}</span></div><section class="wrap product-detail"><div class="detail-gallery"><div class="detail-photo">{photo(p['id'],True,'../')}<span class="photo-label">6個入り</span></div><p class="catalog-note">カラーを選んでカートに追加できます。追加すると画像の自動切り替えが止まります。</p></div><div class="detail-copy"><p class="eyebrow">TCEvolutions / アルミ製ダメージカウンター</p><h1>{p['name']}</h1><p class="detail-range">{p['range']}<span>のダメージを表示 / 6個入り</span></p><p class="price detail-price">¥5,480 <small>税込</small></p><details class="product-disclosure"><summary>商品詳細を開く</summary><p class="detail-description">{p['desc']}</p>{contents_summary(p)}</details>{color_picker(p)}<a class="button preorder-link" data-preorder href="../preorder.html?product={p['id']}">予約注文について <span>→</span></a><button class="button add-button" data-add="{p['id']}" aria-label="{p['name']}をカートに入れる">カートに入れる <span aria-hidden="true">＋</span></button><p class="detail-discount">{other['name']}と各1点で、合計10,480円（税込）。<br>単品合計10,960円から480円引き。<br>割引はカートに自動で反映されます。</p><p class="launch-note"><strong>2026年10月 入荷予定</strong><span>現在は販売準備中です。カートでは組み合わせと金額を確認できます。</span></p></div></section>{official_gallery}<section class="section wrap detail-bottom"><div><p class="eyebrow">商品内容</p><h2>6個の内訳</h2><p class="small">各カウンターの6面に、以下の数字が刻印されています。</p><dl class="spec-list">{rows}<div><dt>素材・加工</dt><dd>アルミニウム / CNC加工</dd></div><div><dt>カラー</dt><dd>全10色</dd></div></dl></div><div><p class="eyebrow">組み合わせて使う</p><h2>{other['range']}も必要な方へ</h2><a class="related-product" data-test-link href="{other['id']}.html">{photo(other['id'],False,'../')}<div><h3>{other['name']}</h3><p>6個入り / ¥5,480（税込）</p><span class="detail-link">商品詳細を見る ↗</span></div></a><p class="small">両方を各1点選ぶと、12個で10,480円（税込）。<br>送料は販売開始前にご案内します。</p></div></section><section class="section wrap related-accessories"><h2>マーカーも一緒に</h2><div class="related-accessory-links"><a href="ability.html">特性使用済みマーカー <span>→</span></a><a href="condition.html">どく・やけどマーカー <span>→</span></a></div></section></main>'''+footer('../')+cart('../')
 root.joinpath('products',p['id']+'.html').write_text(html)
# Existing bundle URLs continue to work, but lead into the same individual-product cart.
for slug,is_full in [('damage-full',False),('tournament-full',True)]:
 title='ダメージカウンターの組み合わせ' if not is_full else 'ダメージカウンター・マーカーのご案内'
 extra='<p>4種類を各1点選ぶと、商品合計15,980円（税込・予定価格）です。特性使用済みマーカーとどく・やけどマーカーは、それぞれ単品3,280円（税込・予定価格）です。</p><a class="detail-link" href="../#products">商品一覧へ →</a>' if is_full else '<button class="button" data-add-pair>ローダメージとハイダメージを各1点入れる <span aria-hidden="true">＋</span></button>'
 html=head(title,'必要な種類を単品から選び、対象の組み合わせでまとめ買い割引。','../')+header('../')+f'''<main id="main" class="section wrap legacy-page"><p class="eyebrow">商品選びのご案内</p><h1>{title}</h1><p>ローダメージとハイダメージは、それぞれ6個入り・5,480円（税込）。必要な種類をカートに追加してお選びください。</p><p>両方を各1点選ぶと、480円のまとめ買い割引が自動で適用されます。商品合計は10,480円（税込）です。</p><div class="legacy-products"><a href="lower.html">{photo('lower',True,'../')}<h2>ローダメージ</h2><p>10〜120 / 6個入り</p></a><a href="higher.html">{photo('higher',True,'../')}<h2>ハイダメージ</h2><p>130〜240 / 6個入り</p></a></div>{extra}</main>'''+footer('../')+cart('../')
 root.joinpath('products',slug+'.html').write_text(html)
print('Built store homepage and four product pages')

# Shared detail-page structure for upcoming accessory products.
accessories=[dict(id='ability',name='特性使用済みマーカー',label='ABILITY USED',desc='特性を使ったことを、カードのそばでわかりやすく。'),dict(id='condition',name='どく・やけどマーカー',label='状態異常マーカー',desc='どく・やけどの状態を、カードのそばに表示。'),dict(id='case',name='収納ケース',label='カウンター・マーカー用',desc='対戦に使うカウンターやマーカーを、ひとつにまとめて。')]
for item in accessories:
 spec=accessory_specs[item['id']]
 html=head(item['name'],item['desc'],'../')+header('../')+f'''<main id="main"><div class="wrap breadcrumb"><a href="../#products">商品一覧</a><span>/</span><span>{item['name']}</span></div><section class="wrap product-detail">{gallery(item)}<div class="detail-copy"><p class="eyebrow">TCEvolutions / {item['label']}</p><h1>{item['name']}</h1><p class="detail-description">{item['desc']}</p><p class="product-descriptor">{spec[0]}</p>{reference_price(item['id'])}<details class="product-disclosure"><summary>商品詳細を開く</summary><p class="detail-description">{spec[1]}</p></details><a class="button preorder-link" href="../preorder.html?product={item['id']}">予約注文について <span>→</span></a><button class="button add-button" data-add="{item['id']}" aria-label="{item['name']}をカートに入れる">カートに入れる <span>＋</span></button><p class="launch-note"><strong>Coming Soon</strong><span>現在は販売準備中です。お届け予定と最終価格は、受付開始前にご案内します。</span></p><a class="detail-link accessory-back" href="../#products">商品一覧へ →</a></div></section><section class="section wrap detail-bottom"><div><p class="eyebrow">商品について</p><h2>商品情報</h2><dl class="spec-list"><div><dt>内容</dt><dd>{spec[2]}</dd></div><div><dt>素材・加工</dt><dd>{spec[3]}</dd></div><div><dt>販売予定価格</dt><dd>¥{accessory_data[item['id']]['planned_jpy']:,}（税込・送料別）</dd></div></dl><p class="small">メーカー情報確認日：2026年9月26日</p><a class="detail-link" href="{accessory_data[item['id']]['source']}" target="_blank" rel="noopener noreferrer">メーカーの商品情報を見る ↗</a></div><div><p class="eyebrow">あわせて選ぶ</p><h2>ダメージカウンター</h2><p class="detail-description">ロー・ハイ各1点、計12個で10,480円（税込）。<br>単品合計10,960円から480円引き。</p><p class="small">この割引はダメージカウンター2種類の組み合わせが対象です。</p><button class="button" data-add-pair>ロー・ハイを各1点カートへ <span>＋</span></button></div></section></main>'''+footer('../')+cart('../')
 root.joinpath('products',item['id']+'.html').write_text(html)

story=head('TCEが生まれた物語','親子の気づきから始まったTCEvolutions。試作の経緯、アルミの加工・着色、プレイヤーとともに歩むものづくり。')+header()+(Path(__file__).parent/'story-content.html').read_text()+footer()+cart()
root.joinpath('story.html').write_text(story)
preorder=head('予約注文について','予約受付に向けた商品・カラー・数量の確認。')+header()+'''<main class="wrap preorder-page section" id="main"><p class="eyebrow">予約注文</p><h1>予約内容の確認</h1><p class="launch-note"><strong>予約受付は準備中です</strong><span>現在、この画面から注文・予約は送信されません。表示価格は販売予定価格です。送料・お届け予定などの受付条件が確定してから開始します。</span></p><form data-preorder-form><label>商品<select name="product"><option value="lower">ローダメージ 6個入り</option><option value="higher">ハイダメージ 6個入り</option><option value="ability">特性使用済みマーカー</option><option value="condition">どく・やけどマーカー</option><option value="case">収納ケース</option></select></label><label data-preorder-color>カラー<select name="color">'''+''.join(f'<option value="{key}">{name}</option>' for key,name,_ in colors)+'''</select></label><label>数量<input name="quantity" type="number" value="1" min="1" max="99" step="1"></label><p data-preorder-total role="status"></p><p class="small">送料・発送予定・予約条件は確定後に掲載します。</p><button class="button" type="button" disabled>予約受付準備中</button></form><a class="detail-link" href="./#products">商品一覧へ戻る →</a></main>'''+footer()+cart()
root.joinpath('preorder.html').write_text(preorder)
