from pathlib import Path
from html import escape
root=Path(__file__).resolve().parents[1]/'store'
v='20260926-15'
photos={
'lower':'https://tcevolutions.com/cdn/shop/files/Damage_Counter_Dice_TCEVOLUTIONS_3.jpg?v=1742269932&width=1200',
'higher':'https://tcevolutions.com/cdn/shop/files/Damage_Counter_Dice_TCEVOLUTIONS_2.jpg?v=1742347748&width=1200',
'ability':'https://tcevolutions.com/cdn/shop/files/bk-closeup-metal-pokemon-tcg-markers-aluminum-us.jpg?v=1768006715&width=1200',
'condition':'https://tcevolutions.com/cdn/shop/files/7B2783A1-62B4-43B6-96C0-BC7A64C24586.png?v=1782411405&width=1200'}
products=[dict(id='lower',name='ローダメージ',range='10〜120',desc='10〜60を表示するカウンターが4個、70〜120が2個。小さなダメージを刻む場面や、ダメカンを少しずつのせる場面に。',rows=[('10・20・30・40・50・60','12mm / 4個'),('70・80・90・100・110・120','13mm / 2個')]),dict(id='higher',name='ハイダメージ',range='130〜240',desc='130〜180を表示するカウンターが4個、190〜240が2個。大きなダメージを、複数の小さなカウンターに分けずに表示できます。',rows=[('130・140・150・160・170・180','13mm / 4個'),('190・200・210・220・230・240','14mm / 2個')])]
def photo(k,eager=False):
 return f'<img src="{photos[k]}" alt="TCEvolutions {dict(lower="ローダメージ6個入り",higher="ハイダメージ6個入り",ability="特性使用済みマーカー",condition="やけど・どくマーカー")[k]}のメーカー商品写真" width="1200" height="1200" loading="{"eager" if eager else "lazy"}">'
def head(title,desc,p='./'):
 return f'<!doctype html>\n<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#191919"><meta name="description" content="{escape(desc)}"><title>{title}｜TAIBAL SUPPLY</title><link rel="stylesheet" href="{p}styles.css?v={v}"></head><body><a class="skip-link" href="#main">本文へ</a>'
def header(p='./'):
 return f'''<div class="announcement">2026年10月 入荷予定 <span>ただいま販売準備中</span></div>
<header class="site-header"><div class="wrap nav"><a class="brand" href="{p}" aria-label="TAIBAL SUPPLY ホーム">TAIBAL<span>SUPPLY</span></a><nav aria-label="メインメニュー"><a data-test-link href="{p}#products">商品一覧</a><a data-test-link href="{p}#craft">ブランドについて</a><a data-test-link href="{p}#faq">ご利用案内</a></nav><button class="cart-trigger" data-cart-open aria-haspopup="dialog" aria-controls="cart-dialog">カート <span data-cart-count>0</span></button></div></header>'''
def footer(p='./'):
 return f'''<footer><div class="wrap footer-grid"><div><a class="brand" href="{p}">TAIBAL<span>SUPPLY</span></a><p>海外のカードサプライを、国内からお届け。</p></div><div class="footer-links"><a href="{p}legal.html">特定商取引法に基づく表記</a><a href="{p}privacy.html">プライバシーポリシー</a><a href="mailto:torataku777@gmail.com">お問い合わせ</a></div></div></footer>'''
def cart(p='./'):
 return f'''<div class="cart-dock" data-cart-dock hidden><div><span data-dock-count></span><strong data-dock-total></strong><small data-dock-discount></small></div><button class="button" data-cart-open>カートを見る <span aria-hidden="true">→</span></button></div>
<dialog id="cart-dialog" class="cart-dialog" aria-labelledby="cart-title"><div class="cart-header"><div><p class="eyebrow">選んだ商品</p><h2 id="cart-title">カート</h2></div><button class="close-button" data-cart-close aria-label="カートを閉じる" autofocus>×</button></div><div class="cart-scroll"><div data-cart-empty><p class="empty-title">カートに商品が入っていません。</p><p>必要な種類を、6個入り1点から選べます。</p><button class="button" data-cart-close>商品を選ぶ</button></div><div data-cart-content hidden><div data-cart-items></div><div class="cart-offer" data-cart-offer></div><div class="cart-totals"><div><span>商品小計</span><span data-subtotal></span></div><div class="discount-row" data-discount-row hidden><span>まとめ買い割引 <small data-pairs></small></span><strong data-discount></strong></div><div class="total-row"><span>商品合計 <small>税込</small></span><strong data-total></strong></div><p class="small">送料は販売開始前にご案内します。</p></div><div class="checkout-area"><p class="launch-note" data-launch-note><strong>2026年10月 入荷予定</strong><span>現在は販売準備中です。カートに入れても注文・予約にはなりません。</span></p><a class="button checkout-link" data-checkout hidden>購入手続きへ</a><p class="small" data-checkout-status hidden></p><button class="continue-button" data-cart-close>商品選びを続ける</button></div></div></div><p class="sr-only" data-cart-announcement role="status" aria-live="polite"></p></dialog>
<div class="toast" role="status" aria-live="polite" data-toast hidden></div><noscript><p class="wrap noscript">カートを使うにはJavaScriptを有効にしてください。商品情報は各詳細ページでご覧いただけます。</p></noscript>
<script src="{p}checkout-config.js?v={v}"></script><script src="{p}cart-model.js?v={v}"></script><script src="{p}app.js?v={v}"></script></body></html>'''
def card(p):
 return f'''<article class="shop-product"><a class="shop-photo" data-test-link href="./products/{p['id']}.html" aria-label="{p['name']}の商品詳細">{photo(p['id'])}<span class="photo-label">6個入り</span></a><div class="shop-product-body"><div class="product-heading"><div><p class="product-brand">TCEvolutions</p><h3>{p['name']}</h3></div><p class="range">{p['range']}<small>表示できるダメージ</small></p></div><p class="product-descriptor">アルミ製ダメージカウンター / 6個入り</p><div class="product-bottom"><p class="price">¥5,480 <small>税込</small></p><a class="detail-link" data-test-link href="./products/{p['id']}.html">内容・サイズ <span aria-hidden="true">↗</span></a></div><button class="button add-button" data-add="{p['id']}" aria-label="{p['name']}をカートに入れる">カートに入れる <span aria-hidden="true">＋</span></button></div></article>'''
index=head('TCEvolutions ダメージカウンター','金属の質感が、いつもの対戦にこだわりを。TCEvolutionsのアルミ製ダメージカウンターを6個入り1点から。対象の組み合わせでまとめ買い割引。')+header()+f'''<main id="main">
<section class="hero"><img class="hero-scene" src="./assets/tce-tabletop.webp" alt="金属製ダメージカウンター、マーカー、収納ケースを卓上に並べたコーディネートイメージ" width="1448" height="1086" fetchpriority="high"><div class="hero-veil"></div><div class="wrap hero-inner"><div class="hero-copy"><p class="hero-brand">TCEvolutions</p><p class="eyebrow">こだわりのポケカサプライ</p><h1>対戦を、<br>もっと美しく。</h1><p class="hero-lead">金属の質感が、<br class="mobile-br">いつもの対戦にこだわりを。</p><p class="hero-description">見やすい数字と、アルミ削り出しの仕上がり。<br>手元の道具にも、自分らしい選択を。</p><a class="button hero-cta" href="#products">ダメージカウンターを選ぶ <span aria-hidden="true">→</span></a><p class="hero-price"><span>6個入り</span><strong>¥5,480</strong><small>税込</small></p></div></div><p class="hero-caption">コーディネートイメージ / ケース・マーカー等は6個入り商品に含まれません。</p></section>
<div class="benefit-strip"><div class="wrap benefit-grid"><div><span class="benefit-index">01</span><p><strong>アルミ削り出し</strong><span>金属ならではの質感</span></p></div><div><span class="benefit-index">02</span><p><strong>必要な種類を、1点から</strong><span>6個入りの商品を組み合わせて</span></p></div><div><span class="benefit-index">03</span><p><strong>国内からお届け</strong><span>入荷後に検品して発送</span></p></div></div></div>
<section id="products" class="section wrap catalog"><span id="singles" class="anchor-alias"></span><span id="sets" class="anchor-alias"></span><div class="section-heading"><div><p class="eyebrow">ダメージカウンター</p><h2>必要なものだけ、<br class="mobile-br">ひとつから。</h2></div><p>使いたい数字に合わせて選べる2種類。<br>どちらも、6個入りでお届けします。</p></div><div class="shop-grid">{card(products[0])}{card(products[1])}</div><div class="bundle-note"><div><span class="offer-label">まとめ買い割引</span><p>2種類を一緒に選ぶと、<strong>480円引き。</strong></p></div><p>ローダメージ・ハイダメージ各1点で自動適用。<br>同じ種類だけの購入は対象外です。</p><button class="bundle-cart" data-cart-open>カートを確認する <span aria-hidden="true">→</span></button></div><p class="catalog-note">商品一覧はメーカーの商品写真です。販売カラーは入荷後にご案内します。</p></section>
<section id="craft" class="craft-section"><div class="wrap craft-grid"><div class="craft-photo"><img src="https://cdn.shopify.com/s/files/1/0813/2188/6018/files/IMG_7184_480x480.jpg?v=1693871287" alt="アルマイト加工の保持部分が付いた、製造途中のアルミ製カウンター" width="480" height="480" loading="lazy"><p>メーカー公開の製造工程写真</p></div><div class="craft-copy"><p class="eyebrow">TCEvolutionsのものづくり</p><h2>アルミを削り出し、<br>数字を刻む。</h2><p>アルミの塊を機械で削って成形し、<br>アルマイト処理で表面を着色。<br>最後にレーザーで数字を刻印しています。</p><p>ダイスの目を10倍して読み替える必要がなく、<br>表示された数字でダメージを確認できます。</p><a class="detail-link" href="https://tcevolutions.com/pages/how-tc-evolutions-products-are-made" target="_blank" rel="noopener noreferrer">メーカーの製造工程を見る ↗</a></div></div></section>
<section id="story" class="section wrap story-grid"><div><p class="eyebrow">ブランドのはじまり</p><h2>きっかけは、<br>息子とのポケカでした。</h2><span class="story-year" aria-hidden="true">2016</span></div><div><p>2016年、当時11歳だったAaronは、ダイスの目を10倍してダメージを計算するのに苦戦していました。</p><p>最初からダメージの数字が書かれていれば、もっとわかりやすい。そのアイデアを、製造業の経験を持つ父Steveが形にしました。</p><p>同年後半には最初の試作品が完成。<br>TCEvolutionsのダメージカウンターは、親子の対戦から生まれました。</p><a class="detail-link" href="https://tcevolutions.com/pages/our-story" target="_blank" rel="noopener noreferrer">メーカーの開発ストーリーを読む ↗</a></div></section>
<section class="accessories-section"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">今後の取り扱い予定</p><h2>マーカーも、<br class="mobile-br">順次入荷予定。</h2></div><p>販売価格とカラーは、入荷後にご案内します。</p></div><div class="accessory-grid"><article>{photo('ability')}<div><h3>特性使用済みマーカー</h3><p>特性を使ったポケモンの目印に。</p><span>販売準備中</span></div></article><article>{photo('condition')}<div><h3>やけど・どくマーカー</h3><p>特殊状態を、カードのそばに表示。</p><span>販売準備中</span></div></article></div></div></section>
<section id="faq" class="section wrap faq-grid"><div><p class="eyebrow">ご利用案内</p><h2>よくあるご質問</h2></div><div class="faq"><details><summary>1点に何個入っていますか？</summary><p>ローダメージ・ハイダメージともに、1点につきカウンター6個入りです。カウンター1個ずつのばら売りではありません。数字とサイズの内訳は、それぞれの商品詳細で確認できます。</p></details><details><summary>まとめ買い割引の条件を教えてください。</summary><p>ローダメージとハイダメージ各1点を1組として、1組につき480円を自動で割り引きます。各1点なら、商品小計10,960円から480円引きの10,480円（税込）です。同じ種類だけの購入には適用されません。</p></details><details><summary>いま注文できますか？</summary><p>現在は販売準備中で、初回入荷は2026年10月を予定しています。カートでは商品の組み合わせと金額を確認できますが、注文・予約・在庫の確保は行われません。販売開始日は、このサイトでお知らせします。</p></details><details><summary>メイン写真の商品がすべて届きますか？</summary><p>メイン写真はコーディネートイメージです。収納ケース・マーカー・カードなどは、6個入りのダメージカウンターに含まれません。購入する商品の内容は、各商品ページでご確認ください。</p></details><details><summary>カラーは選べますか？</summary><p>販売するカラーは、入荷後に確定します。掲載写真のカラーは参考例です。カラーが確定してから購入受付を開始します。</p></details><details><summary>送料と発送日数を教えてください。</summary><p>TAIBAL SUPPLYが国内で受け取り、検品してから発送します。送料・発送日数・返品条件は、販売開始前に掲載します。</p></details><details><summary>TCEvolutionsとの関係を教えてください。</summary><p>TAIBAL SUPPLYはTCEvolutionsから直接仕入れ、国内で販売します。日本総代理店・独占代理店ではありません。</p></details></div></section><section class="closing-section"><div class="wrap"><p class="eyebrow">TCEvolutions / TAIBAL SUPPLY</p><h2>対戦を、もっと美しく。</h2><a class="button" href="#products">商品を選ぶ <span aria-hidden="true">→</span></a></div></section></main>'''+footer()+cart()
root.joinpath('index.html').write_text(index)
for p in products:
 other=next(q for q in products if q!=p)
 rows=''.join(f'<div><dt>{nums}</dt><dd>{qty}</dd></div>' for nums,qty in p['rows'])
 html=head(p['name']+' ダメージカウンター 6個入り',p['desc'],'../')+header('../')+f'''<main id="main"><div class="wrap breadcrumb"><a href="../#products">商品一覧</a><span>/</span><span>{p['name']}</span></div><section class="wrap product-detail"><div class="detail-gallery"><div class="detail-photo">{photo(p['id'],True)}<span class="photo-label">6個入り</span></div><p class="catalog-note">メーカーの商品写真です。販売カラーは入荷後にご案内します。</p></div><div class="detail-copy"><p class="eyebrow">TCEvolutions / アルミ製ダメージカウンター</p><h1>{p['name']}</h1><p class="detail-range">{p['range']}<span>のダメージを表示 / 6個入り</span></p><p class="price detail-price">¥5,480 <small>税込</small></p><p class="detail-description">{p['desc']}</p><button class="button add-button" data-add="{p['id']}" aria-label="{p['name']}をカートに入れる">カートに入れる <span aria-hidden="true">＋</span></button><p class="detail-discount">{other['name']}と各1点の購入で、480円引き。<br>割引はカートに自動で反映されます。</p><p class="launch-note"><strong>2026年10月 入荷予定</strong><span>現在は販売準備中です。カートでは組み合わせと金額を確認できます。</span></p></div></section><section class="section wrap detail-bottom"><div><p class="eyebrow">商品内容</p><h2>6個の内訳</h2><p class="small">各カウンターの6面に、以下の数字が刻印されています。</p><dl class="spec-list">{rows}<div><dt>素材・加工</dt><dd>アルミニウム / CNC加工</dd></div><div><dt>カラー</dt><dd>入荷後にご案内</dd></div></dl></div><div><p class="eyebrow">組み合わせて使う</p><h2>{other['range']}も必要な方へ</h2><a class="related-product" data-test-link href="{other['id']}.html">{photo(other['id'])}<div><h3>{other['name']}</h3><p>6個入り / ¥5,480（税込）</p><span class="detail-link">商品詳細を見る ↗</span></div></a><p class="small">両方を各1点選ぶと、12個で10,480円（税込）。<br>送料は販売開始前にご案内します。</p></div></section></main>'''+footer('../')+cart('../')
 root.joinpath('products',p['id']+'.html').write_text(html)
# Existing bundle URLs continue to work, but lead into the same individual-product cart.
for slug,is_full in [('damage-full',False),('tournament-full',True)]:
 title='ダメージカウンターの組み合わせ' if not is_full else 'ダメージカウンター・マーカーのご案内'
 extra='<p>マーカーは単品での取り扱いを準備しています。販売価格とカラーは、入荷後にご案内します。</p><a class="detail-link" href="../#products">商品一覧へ →</a>' if is_full else '<button class="button" data-add-pair>ローダメージとハイダメージを各1点入れる <span aria-hidden="true">＋</span></button>'
 html=head(title,'必要な種類を単品から選び、対象の組み合わせでまとめ買い割引。','../')+header('../')+f'''<main id="main" class="section wrap legacy-page"><p class="eyebrow">商品選びのご案内</p><h1>{title}</h1><p>ローダメージとハイダメージは、それぞれ6個入り・5,480円（税込）。必要な種類をカートに追加してお選びください。</p><p>両方を各1点選ぶと、480円のまとめ買い割引が自動で適用されます。商品合計は10,480円（税込）です。</p><div class="legacy-products"><a href="lower.html">{photo('lower',True)}<h2>ローダメージ</h2><p>10〜120 / 6個入り</p></a><a href="higher.html">{photo('higher',True)}<h2>ハイダメージ</h2><p>130〜240 / 6個入り</p></a></div>{extra}</main>'''+footer('../')+cart('../')
 root.joinpath('products',slug+'.html').write_text(html)
print('Built store homepage and four product pages')
